### PR TITLE
Enhancement: Add 'Copied' confirmation pop up (#2)

### PR DESCRIPTION
**Pull request by cod500**
I only modified Input.js, input.css, and textarea.css. I created a new function for the popup and created a wrapper for both function on the click event for the copy button. I used setTimeout so the popup would disappear after 2 seconds. I added quite a bit of CSS for the popup. I used the dark theme colors. Let me know if I did something wrong and need to make changes.

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
The behaviour is fine and as expected (thank you!), but see if you can implement it using the `useRef` hook instead of `document.getElementById`, as that is they way it should be done in React.js. If you are not able to do it, let me know and I'll accept this version. Try to implement `useRef` though.

Reference doc: [Refs and the DOM](https://reactjs.org/docs/refs-and-the-dom.html)

**Comment by cod500** [comment]
Ok, I will implement useRef

**Comment by cod500** [comment]
I implemented useRef. Can I ask why the other queryselector method was used for clearBtn and such?

**Comment by cod500** [comment]
Can you please look at the code?

**Comment by HarshKapadia2** [comment]
Hey @cod500, thank you for the PR!
I had a look at the code and have some suggestions.

- The `popup-window` class can be included in the `input.css` file rather than the `textarea.css` file.
- `useRef` can be directly imported in `Input.js` instead of passing it as a prop from `TextArea.js`.
- So there only need to be two modified files.

Also, there have been some changes in the CI/CD process of the repo, so I would encourage opening a new PR with the changes mentioned here. (Do refer to this PR in the new one.)

**Comment by cod500** [comment]
I did the work for you i guess you will probably copy and paste an i wont get credit. I wanted to help but this turned into one task into a thousand. It wook a lot of time to do this and you keep moving the goal post.  Good luck man.

**Pull request closed without merging**
